// Bilingual content. English is the default language; static HTML is generated by build.mjs.
const copy = {
  "en": {
    "nav.research": "Research",
    "nav.publications": "Publications",
    "nav.projects": "Funding",
    "nav.awards": "Awards",
    "nav.background": "Background",
    "profile.role": "Assistant Professor / Distinguished Associate Research Fellow",
    "profile.affiliation": "School of Artificial Intelligence, Shenzhen University",
    "profile.bio": "I work on trustworthy machine learning and computer vision, with a focus on learning from limited or imperfect supervision and making models reliable under uncertainty, occlusion, and distribution shift.",
    "profile.background": "I received my Ph.D. from Central South University in 2024 and subsequently worked there as a postdoctoral researcher. I was also a visiting Ph.D. student at Peng Cheng Laboratory.",
    "recruit.title": "Prospective students",
    "recruit.lead": "I am looking for 2 motivated master's students at the School of Artificial Intelligence, Shenzhen University.",
    "recruit.text": "Strong mathematics and a solid understanding of deep learning fundamentals are especially welcome. I offer hands-on research guidance and computing resources. Outstanding students may be recommended for joint Ph.D. opportunities with Peng Cheng Laboratory and Harbin Institute of Technology, Shenzhen, subject to the relevant admission requirements.",
    "recruit.contact": "Please email me with your CV and a brief description of your research interests.",
    "research.title": "Research interests",
    "research.focusLabel": "Current focus (2024–present):",
    "research.focus": "Domain generalization & test-time adaptation; learning with noisy labels & knowledge distillation; LLM hallucination detection.",
    "publications.title": "Selected publications",
    "projects.title": "Funding & projects",
    "awards.title": "Honors & awards",
    "background.title": "Education & experience",
    "background.experience": "Academic appointments",
    "background.education": "Education",
    "footer.updated": "Last updated: October 2026",
    "footer.back": "Back to top"
  },
  "zh": {
    "nav.research": "研究方向",
    "nav.publications": "论文",
    "nav.projects": "项目",
    "nav.awards": "奖励",
    "nav.background": "教育与经历",
    "profile.role": "助理教授 / 特聘副研究员",
    "profile.affiliation": "深圳大学人工智能学院",
    "profile.bio": "主要研究可信机器学习与计算机视觉，关注有限或不完善监督下的学习，以及模型在不确定性、遮挡与分布变化下的可靠性。",
    "profile.background": "2024 年于中南大学获得博士学位，随后在中南大学从事博士后研究；曾在鹏城实验室开展访问博士研究。",
    "recruit.title": "招生",
    "recruit.lead": "拟招收 2 名深圳大学人工智能学院硕士研究生。",
    "recruit.text": "优先考虑数学基础扎实、深度学习基础理论掌握较好的同学。提供科研指导与算力资源；优秀者可推荐申请鹏城实验室与哈尔滨工业大学（深圳）的联合培养直博 / 普博机会，具体以相关招生要求为准。",
    "recruit.contact": "欢迎邮件联系，并附简历与简要研究兴趣。",
    "research.title": "研究方向",
    "research.focusLabel": "当前研究重点（2024–至今）：",
    "research.focus": "领域泛化与测试时自适应；噪声标签学习与知识蒸馏；大语言模型幻觉检测。",
    "publications.title": "代表性论文",
    "projects.title": "基金与科研项目",
    "awards.title": "荣誉与奖励",
    "background.title": "教育与经历",
    "background.experience": "学术经历",
    "background.education": "教育背景",
    "footer.updated": "更新于：2026 年 10 月",
    "footer.back": "回到顶部"
  }
};

const data = {
  "publications": [
    {
      "year": "2026",
      "type": "preprint",
      "venue": "arXiv preprint",
      "authors": "J. Liu, L. He, and P. Liu",
      "role": "First author",
      "title": "CoVar: Confidence-Variance-Guided Pseudo-Label Selection for Semi-Supervised Learning",
      "titleZh": "CoVar：置信度—方差引导的半监督学习伪标签选择",
      "paper": "https://arxiv.org/abs/2601.11670",
      "code": "https://github.com/ljs11528/CoVar_Pseudo_Label_Selection"
    },
    {
      "year": "2025",
      "type": "conference",
      "venue": "ICCV 2025 · CCF-A",
      "authors": "P. Liu and J. Liu",
      "role": "Corresponding author",
      "title": "When Confidence Fails: Revisiting Pseudo-Label Selection in Semi-supervised Semantic Segmentation",
      "titleZh": "当置信度失效：重新审视半监督语义分割中的伪标签选择",
      "paper": "https://doi.org/10.1109/ICCV51701.2025.02031",
      "code": "https://github.com/PanLiuCSU/CSL",
      "preprint": "https://arxiv.org/abs/2509.16704",
      "highlight": true
    },
    {
      "year": "2025",
      "type": "journal",
      "venue": "TIP · CCF-A",
      "authors": "L. He, Z. Yi, J. Liu, C. Chen, M. Lu, and Z. Chen",
      "role": "Co-author",
      "title": "ALSP+: Fast Scene Recovery via Ambient Light Similarity Prior",
      "titleZh": "ALSP+：基于环境光相似性先验的快速场景恢复",
      "paper": "https://doi.org/10.1109/TIP.2025.3586514",
      "code": "https://github.com/heyuanlei/ALSP"
    },
    {
      "year": "2025",
      "type": "journal",
      "venue": "TASE · CCF-B",
      "authors": "J. Liu, Z. Jiang, W. Gui, Z. Chen, and C. Zhang",
      "role": "First author",
      "title": "Occlusion Segmentation: Restore and Segment Invisible Areas for Particle Objects",
      "titleZh": "遮挡分割：恢复并分割颗粒目标的不可见区域",
      "paper": "https://doi.org/10.1109/TASE.2024.3450900"
    },
    {
      "year": "2024",
      "type": "journal",
      "venue": "JAS · 中科院 1 区",
      "authors": "Z. Jiang, C. Xu, J. Liu, W. Luo, Z. Chen, and W. Gui",
      "role": "Corresponding author",
      "title": "Dual closed-loop modeling for copper disc casting",
      "titleZh": "铜圆盘浇铸过程的双闭环建模",
      "paper": "https://www.ieee-jas.net/en/article/doi/10.1109/JAS.2023.123777",
      "topicOnly": true
    },
    {
      "year": "2023",
      "type": "journal",
      "venue": "TIM · 中科院 2 区",
      "authors": "J. Liu, Z. Jiang, W. Gui, Z. Chen, W. Luo, and C. Zhang",
      "role": "First author",
      "title": "Hierarchical Packing Model: Estimating the Overall Particle Size Distribution From Surface Images and Permeability Properties",
      "titleZh": "层次堆积模型：基于表面图像与透气性属性估计整体粒径分布",
      "paper": "https://doi.org/10.1109/TIM.2023.3338717"
    },
    {
      "year": "2023",
      "type": "journal",
      "venue": "EAAI · 中科院 1 区",
      "authors": "Z. Jiang, J. Liu, Z. Chen, W. Luo, C. Zhang, and W. Gui",
      "role": "Corresponding author",
      "title": "Overall Particle Size Distribution Estimation Method Based on Kinetic Modeling and Transformer Prediction",
      "titleZh": "基于动力学建模与 Transformer 预测的整体粒径分布估计方法",
      "paper": "https://doi.org/10.1016/j.engappai.2023.107517"
    },
    {
      "year": "2023",
      "type": "journal",
      "venue": "TIE · 中科院 1 区",
      "authors": "J. Liu, Z. Jiang, W. Gui, and Z. Chen",
      "role": "First author",
      "title": "A Novel Particle Size Detection System Based on RGB-Laser Fusion Segmentation With Feature Dual-Recalibration for Blast Furnace Materials",
      "titleZh": "基于 RGB-激光融合分割与特征双重重校准的高炉物料粒径检测系统",
      "paper": "https://doi.org/10.1109/TIE.2022.3219054"
    },
    {
      "year": "2023",
      "type": "journal",
      "venue": "TCSVT · 中科院 1 区",
      "authors": "J. Liu, Z. Jiang, T. Cao, Z. Chen, C. Zhang, and W. Gui",
      "role": "First author",
      "title": "Generated Pseudo-Labels Guided by Background Skeletons for Overcoming Under-Segmentation in Overlapping Particle Objects",
      "titleZh": "利用背景骨架生成伪标签解决重叠颗粒目标欠分割",
      "paper": "https://doi.org/10.1109/TCSVT.2022.3230451"
    },
    {
      "year": "2022",
      "type": "journal",
      "venue": "TIM · 中科院 2 区",
      "authors": "Z. Jiang, J. Yu, J. Liu, Z. Chen, W. Gui, and T. Cao",
      "role": "Corresponding author",
      "title": "A Coke Detection Method Based on Reweighting a Composite Feature for Mixed Material Recognition and Quantification",
      "titleZh": "基于复合特征重加权的混合物料识别与焦炭定量检测方法",
      "paper": "https://doi.org/10.1109/TIM.2022.3216662"
    }
  ],
  "projects": [
    {
      "titleZh": "国家自然科学青年基金（C类）",
      "titleEn": "NSFC Young Scientists Fund (Category C)",
      "topicZh": "基于透气性表征的锌冶炼回转挥发窑旋落物料气流场结构化模型生成方法",
      "topicEn": "Generative construction of airflow-field structured models for zinc-smelting rotary volatile-kiln materials based on permeability characterization",
      "roleZh": "主持",
      "roleEn": "PI",
      "period": "2026.01–2028.12",
      "code": "62503505"
    },
    {
      "titleZh": "国家自然科学基金面上项目",
      "titleEn": "NSFC General Program",
      "topicZh": "考虑老化特性与时频动态耦合的储能锂离子电池内短路早期预警方法",
      "topicEn": "Early warning of internal short circuits in lithium-ion energy-storage batteries with aging and time-frequency coupling",
      "roleZh": "课题子任务负责人",
      "roleEn": "Subtask lead",
      "period": "2026.01–2029.12",
      "code": "62573438"
    },
    {
      "titleZh": "湖南自然科学青年基金（C类）",
      "titleEn": "Hunan Provincial Natural Science Foundation — Young Scientists Fund (Category C)",
      "topicZh": "基于元胞图学习的锌冶炼反应釜结构化模型柔性构建方法研究",
      "topicEn": "Flexible construction of structured reactor models based on cellular graph learning",
      "roleZh": "主持",
      "roleEn": "PI",
      "period": "2025.01–2027.12",
      "code": "2025JJ60424"
    },
    {
      "titleZh": "国家重点研发计划",
      "titleEn": "National Key Research and Development Program",
      "topicZh": "锌冶炼固废循环过程在线检测装备与数字调控技术",
      "topicEn": "Online detection equipment and digital regulation for zinc-smelting solid-waste recycling",
      "roleZh": "课题子任务负责人",
      "roleEn": "Subtask lead",
      "period": "2025.01–2027.12",
      "code": "2024YFC3908003"
    },
    {
      "titleZh": "国家资助博士后研究人员计划（C档）",
      "titleEn": "National Postdoctoral Researcher Funding Program (Category C)",
      "topicZh": "基于渗透分析的锌冶炼挥发窑旋落物料气流场结构化模型拓扑构建方法",
      "topicEn": "Topological construction of airflow-field structured models for zinc-smelting rotary-kiln materials based on permeability analysis",
      "roleZh": "主持",
      "roleEn": "PI",
      "period": "2024.07–2026.07",
      "code": "GZC20251179"
    },
    {
      "titleZh": "中国博士后科学基金特别资助（湖南联合资助）",
      "titleEn": "China Postdoctoral Science Foundation Special Joint Funding",
      "topicZh": "旋落颗粒与气流耦合的锌冶炼挥发窑超图结构化模型拓扑构建",
      "topicEn": "Hypergraph-based topology for coupled particles and airflow in zinc-smelting volatile kilns",
      "roleZh": "主持",
      "roleEn": "PI",
      "period": "2024.07–2026.07",
      "code": "2025T012HN"
    },
    {
      "titleZh": "中南大学研究生创新项目",
      "titleEn": "Central South University Graduate Innovation Project",
      "topicZh": "基于视觉感知与堆积模型的高炉物料粒径分布检测",
      "topicEn": "Blast-furnace material particle-size distribution detection based on visual perception and packing models",
      "roleZh": "主持",
      "roleEn": "PI",
      "period": "2022–2023",
      "code": "2023zzts0619"
    }
  ],
  "awards": [
    {
      "year": "2025",
      "titleZh": "第二届湖南省博士后创新创业大赛",
      "titleEn": "2nd Hunan Provincial Postdoctoral Innovation & Entrepreneurship Competition",
      "levelZh": "铜奖",
      "levelEn": "Bronze Award",
      "issuerZh": "湖南省人力资源和社会保障厅",
      "issuerEn": "Hunan Provincial Department of Human Resources and Social Security"
    },
    {
      "year": "2024",
      "titleZh": "全国总决赛",
      "titleEn": "National competition finals",
      "levelZh": "国家三等奖",
      "levelEn": "National Third Prize",
      "issuerZh": "中国信息通信研究院（代）",
      "issuerEn": "China Academy of Information and Communications Technology"
    },
    {
      "year": "2024",
      "titleZh": "2022–2023 年度中南大学优秀学生",
      "titleEn": "Central South University Outstanding Student · 2022–2023",
      "levelZh": "优秀学生",
      "levelEn": "Outstanding Student",
      "issuerZh": "中南大学",
      "issuerEn": "Central South University",
      "ownZh": "个人获奖",
      "ownEn": "Individual honor"
    },
    {
      "year": "2023",
      "titleZh": "湖南省第十六届研究生创新论坛",
      "titleEn": "16th Hunan Provincial Graduate Student Innovation Forum",
      "levelZh": "优秀论文二等奖",
      "levelEn": "Outstanding Paper · 2nd Prize",
      "issuerZh": "湖南省人民政府学位委员会办公室",
      "issuerEn": "Hunan Provincial Degree Committee Office"
    },
    {
      "year": "2023",
      "titleZh": "中南大学研究生校长创新奖学金",
      "titleEn": "Central South University President’s Innovation Scholarship",
      "levelZh": "创新奖",
      "levelEn": "Innovation Award",
      "issuerZh": "中南大学",
      "issuerEn": "Central South University",
      "ownZh": "个人获奖",
      "ownEn": "Individual honor"
    },
    {
      "year": "2022",
      "titleZh": "湖南省第十五届研究生创新论坛",
      "titleEn": "15th Hunan Provincial Graduate Student Innovation Forum",
      "levelZh": "优秀论文一等奖",
      "levelEn": "Outstanding Paper · 1st Prize",
      "issuerZh": "湖南省人民政府学位委员会办公室",
      "issuerEn": "Hunan Provincial Degree Committee Office"
    },
    {
      "year": "2020",
      "titleZh": "“创响中国”创新创业年会",
      "titleEn": "“Innovation in China” Innovation & Entrepreneurship Annual Meeting",
      "levelZh": "优秀论文奖",
      "levelEn": "Outstanding Paper Award",
      "issuerZh": "中南大学",
      "issuerEn": "Central South University"
    },
    {
      "year": "2018",
      "titleZh": "中南大学第四届矿冶工程化学虚拟仿真设计大赛",
      "titleEn": "4th Mining & Metallurgical Engineering Chemistry Virtual Simulation Competition",
      "levelZh": "一等奖",
      "levelEn": "First Prize",
      "issuerZh": "中南大学",
      "issuerEn": "Central South University"
    }
  ],
  "education": [
    {
      "date": "2020.09–2024.06",
      "dateEn": "2020.09–2024.06",
      "titleZh": "中南大学 · 控制科学与工程",
      "titleEn": "Central South University · Control Science and Engineering",
      "textZh": "博士｜多模态视觉感知",
      "textEn": "Ph.D. · Multimodal visual perception",
      "tag": "Ph.D."
    },
    {
      "date": "2017.09–2020.06",
      "dateEn": "2017.09–2020.06",
      "titleZh": "中南大学 · 控制科学与工程",
      "titleEn": "Central South University · Control Science and Engineering",
      "textZh": "硕士｜单目 3D 重建",
      "textEn": "M.E. · Monocular 3D reconstruction",
      "tag": "M.E."
    },
    {
      "date": "2013.09–2017.06",
      "dateEn": "2013.09–2017.06",
      "titleZh": "中南大学 · 智能科学与技术",
      "titleEn": "Central South University · Intelligent Science and Technology",
      "textZh": "学士｜多目标优化",
      "textEn": "B.E. · Multi-objective optimization",
      "tag": "B.E."
    }
  ],
  "experience": [
    {
      "date": "2026–至今",
      "dateEn": "2026–present",
      "titleZh": "深圳大学 · 人工智能学院",
      "titleEn": "Shenzhen University · School of Artificial Intelligence",
      "textZh": "助理教授/特聘副研究员",
      "textEn": "Assistant Professor / Distinguished Associate Research Fellow",
      "tag": "CURRENT"
    },
    {
      "date": "2024.07–2026.07",
      "dateEn": "2024.07–2026.07",
      "titleZh": "中南大学 · 博士后",
      "titleEn": "Central South University · Postdoctoral Researcher",
      "textZh": "计算机科学｜伪标签学习与复杂过程智能",
      "textEn": "Computer Science · Pseudo-label learning & complex-process intelligence",
      "tag": "POSTDOC"
    },
    {
      "date": "2021.03–2024.05",
      "dateEn": "2021.03–2024.05",
      "titleZh": "鹏城实验室 · 访问博士",
      "titleEn": "Peng Cheng Laboratory · Visiting Ph.D.",
      "textZh": "前沿学术中心｜复杂场景建模与 XR 人机交互",
      "textEn": "Frontier Academic Center · Complex-scene modeling & XR human–computer interaction",
      "tag": "VISITING"
    }
  ],
  "research": [
    {
      "en": {
        "title": "Trustworthy learning",
        "text": "Semi-supervised learning, pseudo-label selection, and uncertainty estimation."
      },
      "zh": {
        "title": "可信学习",
        "text": "半监督学习、伪标签选择与不确定性估计。"
      }
    },
    {
      "en": {
        "title": "Visual perception",
        "text": "Image, video, and 3D segmentation; occlusion and incomplete observations."
      },
      "zh": {
        "title": "视觉感知",
        "text": "图像 / 视频 / 3D 分割，遮挡感知与不完整观测。"
      }
    },
    {
      "en": {
        "title": "Multimodal understanding",
        "text": "Representation learning across vision, language, and structured information."
      },
      "zh": {
        "title": "多模态理解",
        "text": "视觉、语言与结构化信息的协同表示学习。"
      }
    },
    {
      "en": {
        "title": "Structured modeling",
        "text": "Connecting visual perception with mechanism-based models for complex systems."
      },
      "zh": {
        "title": "结构化建模",
        "text": "连接视觉感知与机理模型，研究复杂系统的建模与理解。"
      }
    }
  ]
};

function escapeHtml(value) {
  return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
}

function externalLink(url, label) {
  return '<a href="' + escapeHtml(url) + '" target="_blank" rel="noopener noreferrer">' + escapeHtml(label) + '</a>';
}

function renderSections(lang = 'en') {
  const zh = lang === 'zh';
  const localized = (item, key) => item[key + (zh ? 'Zh' : 'En')];
  const roles = { 'First author': '第一作者', 'Corresponding author': '通讯作者', 'Co-author': '共同作者' };
  const timeline = items => items.map(item => '<li class="dated-item"><span class="date">' + escapeHtml(zh ? item.date : item.dateEn) + '</span><div><strong>' + escapeHtml(localized(item, 'title')) + '</strong><br><span class="muted">' + escapeHtml(localized(item, 'text')) + '</span></div></li>').join('\n');
  return {
    research: data.research.map(item => '<li><strong>' + escapeHtml(item[lang].title) + (zh ? '：</strong> ' : '.</strong> ') + escapeHtml(item[lang].text) + '</li>').join('\n'),
    publications: data.publications.map(item => {
      const title = item.topicOnly ? (zh ? '研究主题：' + item.titleZh : 'Research topic: ' + item.title) : item.title;
      const authors = escapeHtml(item.authors).replace(/J\\. Liu/g, '<strong>J. Liu</strong>');
      const venue = zh ? item.venue : item.venue.replace('中科院 1 区', 'CAS Q1').replace('中科院 2 区', 'CAS Q2');
      const links = [externalLink(item.paper, item.type === 'preprint' ? 'arXiv' : (zh ? '出版页' : 'Paper'))];
      if (item.code) links.push(externalLink(item.code, zh ? '代码' : 'Code'));
      if (item.preprint) links.push(externalLink(item.preprint, 'arXiv'));
      return '<li class="dated-item publication"><span class="date">' + item.year + '</span><div><h3>' + externalLink(item.paper, title) + '</h3><p class="authors">' + authors + ' <span class="muted">· ' + escapeHtml(zh ? roles[item.role] : item.role) + '</span></p><p class="publication-meta"><span class="venue">' + escapeHtml(venue) + '</span>' + (item.highlight ? ' <strong class="highlight">· Highlight</strong>' : '') + ' <span class="link-separator">/</span> ' + links.join(' · ') + '</p></div></li>';
    }).join('\n'),
    projects: data.projects.map(item => '<li><strong>' + escapeHtml(localized(item, 'title')) + '</strong> <span class="muted">· ' + escapeHtml(localized(item, 'role')) + ' · ' + escapeHtml(item.period) + ' · No. ' + escapeHtml(item.code) + '</span><br><span class="project-topic">' + escapeHtml(localized(item, 'topic')) + '</span></li>').join('\n'),
    awards: data.awards.map(item => '<li class="dated-item"><span class="date">' + item.year + '</span><div><strong>' + escapeHtml(localized(item, 'level')) + '</strong> · ' + escapeHtml(localized(item, 'title')) + '<br><span class="muted">' + escapeHtml(localized(item, 'issuer')) + (item.ownZh ? ' · ' + escapeHtml(localized(item, 'own')) : '') + '</span></div></li>').join('\n'),
    education: timeline(data.education),
    experience: timeline(data.experience)
  };
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { copy, data, renderSections, escapeHtml };
}

if (typeof document !== 'undefined') {
  let lang = 'en';
  const toggle = document.getElementById('lang-toggle');
  toggle.hidden = false;
  function applyLanguage() {
    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
    document.title = lang === 'zh' ? '刘金狮 | 深圳大学' : 'Jinshi Liu | Shenzhen University';
    document.querySelectorAll('[data-copy]').forEach(element => {
      element.textContent = copy[lang][element.dataset.copy];
    });
    document.querySelector('meta[name="description"]').content = copy[lang]['profile.bio'];
    const sections = renderSections(lang);
    document.querySelectorAll('[data-content]').forEach(element => {
      element.innerHTML = sections[element.dataset.content];
    });
    toggle.textContent = lang === 'zh' ? 'English' : '中文';
    toggle.setAttribute('aria-label', lang === 'zh' ? 'Switch to English' : '切换到中文');
  }
  toggle.addEventListener('click', () => {
    lang = lang === 'en' ? 'zh' : 'en';
    applyLanguage();
  });
}
